#!/usr/bin/env bash
# Install git hooks from scripts/hooks/ into .git/hooks/
# Run once after cloning: make setup  (or bash scripts/install-hooks.sh)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOKS_SRC="$REPO_ROOT/scripts/hooks"
HOOKS_DST="$REPO_ROOT/.git/hooks"

if [ ! -d "$HOOKS_DST" ]; then
    echo "Error: .git/hooks not found — are you in a git repository?"
    exit 1
fi

# A shim, not a copy.
#
# This used to `cp`, and a copy drifts silently: on 2026-08-22 the pre-push checks were
# edited three times and every push that day ran the version installed on 2026-08-03,
# because nothing re-runs the installer and nothing says the two have diverged. The
# symptom was a hook flagging a commit that the tracked hook passes, which reads as a
# bug in the check rather than as a stale install.
#
# So .git/hooks/<name> is now two lines that exec the tracked file. It cannot go stale,
# it follows branch checkouts, and it avoids symlinks, which are awkward on Windows.
for hook in "$HOOKS_SRC"/*; do
    name="$(basename "$hook")"
    dst="$HOOKS_DST/$name"
    cat > "$dst" <<SHIM
#!/usr/bin/env bash
# Generated by scripts/install-hooks.sh — edit scripts/hooks/$name instead.
exec "\$(git rev-parse --show-toplevel)/scripts/hooks/$name" "\$@"
SHIM
    chmod +x "$dst"
    echo "Installed: .git/hooks/$name -> scripts/hooks/$name"
done

echo ""
echo "Done. Hooks will run automatically on git push."
echo "To skip in an emergency: git push --no-verify"
echo ""
echo "pre-push runs fmt, clippy and tests, and also rejects commit messages that"
echo "state a performance number without saying how it was measured (see"
echo "CONTRIBUTING.md → Performance claims). Skip just that one with:"
echo "  FOX_SKIP_PERF_CHECK=1 git push"
